steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - create
      - --project=parser-387505
      - --region=asia-south1
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - deploy
      - --project=parser-387505
      - --version=$SHORT_SHA
      - --quiet
    env:
      - 'PROJECT_ID=parser-387505'
      - 'SHORT_SHA=$_SHORT_SHA'
timeout: '10m'
